# локальные настройки для разработки
spring:
  application:
    name: todo-backend
  datasource: # данные для соединения с БД
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
server:
  port: 8085
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/javabegin_ssl.pfx
    key-store-password: 123